//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMovie.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheMovie.Application.Resources.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified genre does not exist..
        /// </summary>
        public static string Movie_GenreId_Exists {
            get {
                return ResourceManager.GetString("Movie_GenreId_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre is required..
        /// </summary>
        public static string Movie_GenreId_Required {
            get {
                return ResourceManager.GetString("Movie_GenreId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket price must be greater than zero..
        /// </summary>
        public static string Movie_Price_GreaterThan {
            get {
                return ResourceManager.GetString("Movie_Price_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid rating is required..
        /// </summary>
        public static string Movie_Rating_Invalid {
            get {
                return ResourceManager.GetString("Movie_Rating_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release year cannot be in the future..
        /// </summary>
        public static string Movie_ReleaseYear_Future {
            get {
                return ResourceManager.GetString("Movie_ReleaseYear_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release year must be greater than 1888..
        /// </summary>
        public static string Movie_ReleaseYear_Min {
            get {
                return ResourceManager.GetString("Movie_ReleaseYear_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synopsis is required..
        /// </summary>
        public static string Movie_Synopsis_Required {
            get {
                return ResourceManager.GetString("Movie_Synopsis_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be longer than {MaxLength} characters..
        /// </summary>
        public static string Movie_Title_MaxLength {
            get {
                return ResourceManager.GetString("Movie_Title_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string Movie_Title_Required {
            get {
                return ResourceManager.GetString("Movie_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A movie with this title already exists..
        /// </summary>
        public static string Movie_Title_Unique {
            get {
                return ResourceManager.GetString("Movie_Title_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number must be greater than or equal to 1..
        /// </summary>
        public static string Pagination_PageNumber_Min {
            get {
                return ResourceManager.GetString("Pagination_PageNumber_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be between {Min} and {Max}..
        /// </summary>
        public static string Pagination_PageSize_Range {
            get {
                return ResourceManager.GetString("Pagination_PageSize_Range", resourceCulture);
            }
        }
    }
}
