<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\TheMovie.Domain\TheMovie.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="MediatR" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Validations.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Validations.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Validations.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Validations.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
